### ISSUE TITLE
Include 16-17 data

### ISSUE THREAD

**Issue by daranzolin** [daranzolin/rCAEDDATA#2]

**Comment by dcaud** [comment]
Hi. Is there any chance this would be updated with more recent data?

**Comment by daranzolin** [comment]
Hi @dcaud, 

Thanks for your interest! But no, in retrospect, I no longer think this is a good way to package this much data. Ideally the CA DoE would create an API, or someone would create a more easily updated database (I suppose I might this summer...). Another tentative option would be [the cadoe package,](https://github.com/ir-sfsu/cadoe) thought it hasn't been thoroughly tested, and I've only used it a couple times for one-off projects.
